In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_log_error, make_scorer

In [2]:
df = pd.read_csv(r"C:\Users\bas41\Downloads\train kaggle.csv")
test = pd.read_csv(r"C:\Users\bas41\Downloads\test kaggle.csv")
df.head()

   age     sex     bmi  children smoker     region      charges  id
0   43    male  26.030         0     no  northeast   6837.36870   1
1   58  female  28.215         0     no  northwest  12224.35085   2
2   53    male  31.350         0     no  southeast  27346.04207   3
3   54    male  29.200         1     no  southwest  10436.09600   4
4   19    male  34.900         0    yes  southwest  34828.65400   5

In [3]:
def to_good_appearance(df: pd.DataFrame):
    df['smoker'] = np.int8(df['smoker'] == 'yes')
    
    df['male'] = np.int8(df['sex'] == 'male')
    
    df['northeast'] = np.int8(df['region'] == 'northeast')
    df['northwest'] = np.int8(df['region'] == 'northwest')
    df['southeast'] = np.int8(df['region'] == 'southeast')
    
    del df['sex']
    del df['region']
    del df['id']
    
    return df

df_v2 = to_good_appearance(df)
test_v2 = to_good_appearance(test)

df_v2

,age,bmi,children,smoker,charges,male,northeast,northwest,southeast
0,43,26.030,0,0,6837.36870,1,1,0,0
1,58,28.215,0,0,12224.35085,0,0,1,0
2,53,31.350,0,0,27346.04207,1,0,0,1
3,54,29.200,1,0,10436.09600,1,0,0,0
4,19,34.900,0,1,34828.65400,1,0,0,0
...,...,...,...,...,...,...,...,...,...
664,18,31.350,4,0,4561.18850,0,1,0,0
665,39,23.870,5,0,8582.30230,0,0,0,1
666,58,25.175,0,0,11931.12525,1,1,0,0
667,37,47.600,2,1,46113.51100,0,0,0,0
668,55,29.900,0,0,10214.63600,1,0,0,0

In [4]:
def add_features(df: pd.DataFrame):

    df['children'] = df['children'].where(df['children'] < 3, 3)

    df['age*bmi'] = df['age'] * df['bmi']
    df['age*children'] = df['age'] * df['children']
    df['bmi*children'] = df['bmi'] * df['children']
    df['smoker*bmi'] = df['smoker'] * df['bmi']
    df['age*smoker'] = df['age'] * df['smoker']
    df['male*bmi'] = df['male'] * df['bmi']
    df['age**2'] = df['age'] ** 2
    df['bmi**2'] = df['bmi'] ** 2
    df['children**2'] = df['children'] ** 2

    if 'charges' in df.columns:
        df['charges'] = np.log1p(df['charges'])

    feature_columns = [el for el in list(df.columns) if el != 'charges']
    
    return df, feature_columns

df_v3, feature_columns = add_features(df_v2)
test_v3, _ = add_features(test_v2)

df_v3

,age,bmi,children,smoker,charges,male,northeast,northwest,southeast,age*bmi,age*children,bmi*children,smoker*bmi,age*smoker,male*bmi,age**2,bmi**2,children**2
0,43,26.030,0,0,8.830304,1,1,0,0,1119.29,0,0.00,0.0,0,26.030,1849,677.560900,0
1,58,28.215,0,0,9.411267,0,0,1,0,1636.47,0,0.00,0.0,0,0.000,3364,796.086225,0
2,53,31.350,0,0,10.216364,1,0,0,1,1661.55,0,0.00,0.0,0,31.350,2809,982.822500,0
3,54,29.200,1,0,9.253122,1,0,0,0,1576.80,54,29.20,0.0,0,29.200,2916,852.640000,1
4,19,34.900,0,1,10.458224,1,0,0,0,663.10,0,0.00,34.9,19,34.900,361,1218.010000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664,18,31.350,3,0,8.425558,0,1,0,0,564.30,54,94.05,0.0,0,0.000,324,982.822500,9
665,39,23.870,3,0,9.057574,0,0,0,1,930.93,117,71.61,0.0,0,0.000,1521,569.776900,9
666,58,25.175,0,0,9.386990,1,1,0,0,1460.15,0,0.00,0.0,0,25.175,3364,633.780625,0
667,37,47.600,2,1,10.738883,0,0,0,0,1761.20,74,95.20,47.6,37,0.000,1369,2265.760000,4
668,55,29.900,0,0,9.231675,1,0,0,0,1644.50,0,0.00,0.0,0,29.900,3025,894.010000,0

In [5]:
x_train, x_test, y_train, y_test = train_test_split(df_v3.loc[:, feature_columns], df_v3.loc[:, 'charges'], test_size=0.2, random_state=42, shuffle=True)

def RMSLE(y_true, y_pred):
    y_pred = np.maximum(y_pred, 0)
    return np.sqrt(mean_squared_log_error(y_true, y_pred))

rmsle_scorer = make_scorer(
    RMSLE, 
    greater_is_better=False
)

In [6]:
grid_3 = {
    'n_estimators': range(90, 100),
    'max_depth': range(20, 40),
    'min_samples_leaf': [9],
    # 'regressor__max_features': np.linspace(0.1, 1, 2),
    # 'regressor__max_leaf_nodes': [None] + list(range(45, 50))
}

model = GridSearchCV(
    estimator=RandomForestRegressor(random_state=42, n_jobs=-1),
    param_grid=grid_3,
    cv=5,
    scoring=rmsle_scorer,
    n_jobs=-1,
    verbose=1
)

model.fit(x_train, y_train)

print("\n" + "="*50)
print("ЛУЧШИЕ ПАРАМЕТРЫ:")
print(model.best_params_)
print(f"Лучший CV score: {-model.best_score_:.4f}")

Fitting 5 folds for each of 200 candidates, totalling 1000 fits

==================================================
ЛУЧШИЕ ПАРАМЕТРЫ Random Forest:
{'max_depth': 27, 'min_samples_leaf': 9, 'n_estimators': 99}
Лучший CV score (RMSLE): 0.0428

c:\Users\bas41\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\ma\core.py:2881: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,

In [7]:
RFR = RandomForestRegressor(n_estimators=99, max_depth=24, min_samples_leaf=9, random_state=42)
RFR.fit(x_train, y_train)
y_pred = RFR.predict(x_test)
RMSLE(np.exp(y_test), np.exp(y_pred))

np.float64(0.32226420082624885)

In [8]:
y_pred = np.exp(RFR.predict(test_v2))

In [9]:
y_pred

array([ 8774.02375371,  4739.39919146, 26021.08978806,  9626.85366951,
       36447.17180329,  5671.34616445,  2078.04831262, 14536.02384236,
        4123.43410742, 12563.94575397, 19236.86887444,  8278.20590639,
        5907.64009085, 46974.07680749, 47072.18415382, 46852.16818822,
       12853.5568756 , 47006.30805389,  8095.48618237, 25298.00422217,
        4802.89363612,  9352.97916233,  1774.46751777,  3167.85510634,
       13001.06240164, 11630.03592594, 14525.42843716,  5809.5961349 ,
       11521.23836806,  1793.59961231,  8584.8226188 , 11854.04236825,
        2719.96605828,  5670.31487509,  4730.1040318 ,  7844.04193898,
        3294.07732707,  7435.46706258, 25587.17137817, 44994.61626768,
        4275.15965564,  4250.54226724, 12378.78063366, 13736.28911124,
        5845.76571803, 14089.84460144,  5082.60223542,  5106.39476281,
       46020.12755744,  5807.2327448 , 14558.89059387,  2450.1934633 ,
        6698.60813936,  2127.4234449 , 11078.990287  , 12248.28682918,
        3626.49154843, 40265.49159662, 11374.87037163, 11055.46369557,
       14329.9068169 ,  5757.42573931, 18009.36477259,  7622.82211655,
       10966.14022732,  5670.96312739, 17921.33954862, 13470.1921153 ,
        4973.69210367,  2563.44379542,  6911.81258583,  9672.28655684,
       10254.69738779,  8167.31460358,  8087.0240696 ,  4598.05574369,
        6046.78627601, 12501.15910372,  5581.73177545,  9314.02279158,
        2084.69237616, 26159.82178228,  5679.32317257, 37177.51302538,
       42475.13276208, 42841.27105509,  5928.77424771, 11685.91285388,
        8735.09575876, 13499.41058896, 17780.73416461, 25714.87860901,
       25862.65940838,  5785.11598925, 45268.87016009,  8860.67626109,
       20455.99585849,  2432.60372129, 18985.04103766,  6454.11596654,
        5800.7317994 ,  2111.00520344,  6922.27375622, 14189.49137033,
       14033.55274837,  2427.28699807,  9484.82331803, 25088.93429324,
        2159.35037381, 25470.71658228,  1788.49123268,  4846.79275368,
       12215.50189826, 40269.07539167, 10910.71969712,  3501.44876554,
       13777.33427496, 24926.27365334,  7110.87943312,  3656.91231163,
        6029.13298534,  9273.91218586, 14381.67715923,  3301.04274312,
        5465.66875361,  8750.0185307 ,  7511.25358378, 11242.28630697,
       14435.37046624,  3093.15954502,  4152.3858437 ,  6742.14602019,
        6869.10158022,  7653.18357885,  6316.29209318, 17150.29677643,
        3910.10000772, 35488.57651845, 47123.08321698, 40644.90938037,
        4773.23031363, 11009.81896957,  3339.82040824, 14565.71458994,
        2822.24913111, 25682.64663493,  5421.51195594,  4158.08724326,
       13337.58784782,  5596.94620594, 47166.46154619,  3428.92521852,
        1892.24850331, 40187.68184765,  6399.05214922,  3910.10000772,
       14326.32694364, 10358.73185314, 36494.08131531, 42110.53010858,
       13743.98125894,  2407.31452853, 16062.91544316,  2741.00479896,
        5093.460617  ,  9310.36829374, 47278.66838677, 43294.05927227,
       42442.68993076,  3703.26431121, 11738.54990424,  6448.49032174,
        6748.95131187,  5273.87203758,  2432.18488685, 25781.52125973,
       18197.45816924, 14520.64103303, 17313.99768003, 12537.25470406,
       26021.08978806,  3244.64404662, 10522.9345208 ,  5344.34622448,
        5683.53589098,  4002.47129955,  6633.39352931,  4141.11478619,
       10150.63431284, 12241.96756189,  5128.40096619,  2544.42723235,
        2764.61255839, 42301.01620182, 14534.64913621, 10155.21612155,
        2308.01576441, 13111.20717904,  2505.66830581, 11972.83647258,
        3971.39249614, 26159.82178228,  5837.54774957,  4139.38941464,
       17929.40179661, 18396.38003615, 12384.0603363 ,  4908.22456187,
        9927.06653302,  4681.76948983, 13955.59850114, 12938.45443586,
        9912.05331597, 19404.13297782,  7068.63405802,  4308.48431297,
        5397.99625732, 15796.04871478, 14005.36948494,  5486.70017251,
        2783.85983776,  7523.46108909,  8550.56461451, 46253.63501199,
        2675.85962391, 36667.36925988,  2055.58072023,  1793.86252985,
       10198.33673559, 13321.4832242 ,  2463.01970095, 11810.88933771,
        5566.01518644, 25588.39032719, 11732.4656809 ,  9927.24824997,
        5420.75638457,  7103.68991612, 46825.26630453,  2558.88586163,
       13914.49394749, 40703.62533071,  3932.38914508,  4921.583312  ,
        1692.63565972,  3438.76472166,  5246.47582073,  5385.17121675,
       13659.52893131,  1776.13097066,  2261.33325506,  9285.32128561,
        4019.86523616, 12400.96949496,  2789.04109386,  4970.43399438,
       13738.93445774,  4814.31311471, 11816.00485243,  6410.03676659,
        8555.16143238, 13992.77426699, 20390.3463031 , 46400.04569007,
       12440.78055481,  6772.86987266, 47278.66838677, 10823.01151713,
        8383.55908635, 10804.52286932, 11505.84814253,  8906.88219424,
       13804.44863427, 14520.64103303,  2427.43586379, 17215.56232835,
        7180.12010782, 42067.54688002,  5668.78910506, 11036.00211117,
       11302.74601441, 14542.51391961,  9602.58411757, 10848.79420296,
       42134.03339432,  2968.05571392, 11404.99342537, 46960.46736392,
        6284.43941704,  3462.34990033,  2710.90842772, 11923.20240266,
       17440.78777444, 11997.56793736,  9257.68815415, 12316.60913679,
       11828.92163891,  4722.8299276 ,  2533.90803171, 37245.9118416 ,
       40163.94193526,  9066.67832018,  4444.15511716, 17999.23774534,
       16093.20004858, 40850.82014855,  2665.71066668, 43546.38157986,
        5878.98315333,  2201.91785308,  6471.36055264,  2467.31681327,
       17863.43555595, 14669.05181751,  2855.19118028, 12603.22217941,
       10975.79578049, 12014.04411418, 46199.0707786 , 14138.18283846,
       25691.03745825,  9145.95179554, 17646.05001288,  5630.61181335,
        8095.48618237,  8948.19822904, 17343.22036465, 12323.95802625,
        3841.84599298, 11240.23872249, 13840.91546   , 11631.27078759,
        5564.96813301, 36381.08346315,  6962.09722725,  2958.86453444,
        5326.21239618, 11195.92113463, 46697.42058079,  9070.66193386,
       14039.33674098,  6946.30143301,  5783.0311207 ,  4971.98067948,
        2694.15108494,  7906.206248  ,  6413.33488539,  2242.66541922,
       12066.91117661,  7458.1908206 ,  5429.01812149,  4343.28078292,
       12104.55618182,  3794.65121239, 42274.5181057 , 37126.86747355,
       47241.24588474,  4143.07012954,  8212.98297567,  6700.80771555,
        2417.39642909, 24869.09837033,  7461.16488958, 19154.01782837,
       46432.46664836,  5619.21465285, 13709.13600493,  5929.15887988,
       12168.89928096, 12619.52049019, 19547.96942502, 12502.3371357 ,
        6026.85499517,  5460.45003855,  2971.83674273, 12162.66498275,
       24751.39635752, 11316.06581995, 10264.80855012,  3912.428519  ,
        4456.90600103,  6968.12241214, 11577.00285673,  9581.14374701,
       25629.04007877, 43545.49277658, 11527.47336202,  7377.85387354,
       14598.89359152, 13622.65750148,  8377.20858644,  4221.70410093,
        7946.60510738,  4781.92695855, 10342.62375213,  5425.20836129,
       12072.38999927, 11304.05226586,  4356.25250397,  2544.42723235,
       11231.12487543,  2685.81177664, 13961.12933593,  7529.17311611,
       13076.3512532 , 43089.27731426, 40677.39579882, 46813.42839187,
        5430.2989677 ,  5220.36548475, 14288.94386116,  6911.10483131,
       47008.81165059,  2750.6826085 ,  7170.94296682, 13646.44277596,
       23662.14580405,  4473.28650989,  3190.05934074, 11614.86965997,
        4958.49185   ,  5394.23528416,  7146.57250681,  1696.4596618 ,
       19550.00357869,  8630.17274132,  5929.52332088,  4106.57014081,
        5680.86083625, 13289.7255344 , 19874.46571587,  9200.01899649,
        7363.33128599,  4354.88427242,  5852.90516405,  3749.283937  ,
        6223.12859175,  9564.96514564, 12204.20349195, 11555.57279041,
        5666.09288786,  2993.29118521,  7388.37887433, 45509.12500936,
       42628.86668104,  2207.49651661, 47072.18415382, 36927.64187776,
       12463.4013696 ,  1738.81697491, 14499.0167106 ,  1749.0320976 ,
       12094.4234173 , 36543.86367004, 17931.16181212, 12164.81819817,
        6887.20907067, 13504.19078907,  5277.76693397,  9930.09840697,
        3804.09400529, 12789.20542546, 11146.15665295,  7005.56063959,
        4363.68143033,  4345.40933943,  9391.12248391,  6546.65882542,
       19661.52442528, 14026.20697814,  1941.81737801, 42032.37319714,
       36426.79938905,  3253.70594095,  1885.8844386 , 18785.88804911,
        5971.70042722, 12312.04365249, 14055.8949499 ,  4171.28930133,
        6720.91624522, 11804.26242161,  2540.76301593,  3107.07526655,
        5307.37220992,  2182.39822944,  3213.59814642, 25890.45869798,
        7616.35025595, 42134.03339432, 36381.08346315, 14582.30338342,
       11308.77701437,  5853.12897662, 11703.50939469,  9338.30788325,
       12964.68735496, 17874.46780442, 10857.52647097,  6664.25211729,
       11148.52349921,  8852.49649091,  3060.85945357, 11020.59558338,
        4321.71617714, 11772.39468395, 17610.75357688,  2144.9208606 ,
       10665.33203046, 17929.40179661, 13870.13468624, 46997.66744516,
       46343.56040848,  8649.28582396,  5197.95186922, 36543.86367004,
        1703.42274987, 37126.86747355, 12627.6147519 ,  3646.72594687,
       17215.8652143 ,  5645.72110693,  8053.07725526,  2064.12984248,
        5233.34677288,  5930.30325304,  8932.49638031,  3738.04419462,
       14018.04717357,  7374.4900508 , 25182.26535972, 14775.77659826,
        7019.48817617,  5439.65417122, 12965.23219096, 43546.38157986,
       15796.04871478, 13974.54554389,  4273.28827829,  2712.06787984,
        9563.24261204, 46997.66744516, 11828.83251101,  5467.54375056,
        9867.59105368, 46020.12755744,  1816.99369428, 12621.80115411,
       11362.96457409,  9852.91685462, 11269.60755529, 17367.88201087,
        5908.19081961,  4139.69879062, 12368.06552626, 23360.75542113,
        6042.67046001, 19768.46463462, 46013.473835  , 11913.26198914,
        6114.11755708,  9327.5579222 , 27080.10045234, 43506.42337341,
        1770.53611707, 24692.15695662,  2129.08113325,  3802.93814677,
       46603.5815577 , 10675.91558859,  4785.45206646, 11868.56761493,
       13747.79936123,  6110.67215956,  7596.79530281, 10852.16564269,
        5585.92022063, 25751.85878404,  5673.40064145, 13756.17610424,
       12922.0750584 , 19475.12902416,  7417.10009998,  2215.99006558,
       10628.45321042,  6264.7133639 , 11084.53541743,  7923.60896266,
        4554.23132766,  7921.69771961, 17698.32292958, 11669.98916329,
        1909.61700238,  5246.65035758,  7079.34471806,  7814.591473  ,
        9559.27362876, 11205.50018447, 42429.67266168,  2217.89018096,
       36494.08131531,  1718.87284581, 46570.9154314 , 32966.15524373,
       10414.96896075, 13311.08153908, 14352.73244639,  4758.87270213,
        3971.39249614, 19199.40049601, 11064.71033506,  8934.25294117,
        5729.6769762 , 45187.00175292, 11785.3395927 ,  6361.86484495,
        2667.45424589,  7163.44396258,  6074.32986094, 43269.10165644,
       43080.12875236, 13905.18886988, 46997.66744516,  6503.53667224,
        7389.75282055, 34312.9974111 , 13039.32607464, 26914.08714492,
        2466.33148421, 44830.20012038, 43450.50019309, 37177.51302538,
       11935.01721354,  7031.31110178, 13972.63193285,  2927.50006365,
       17471.85339806, 46089.60444735,  3575.50624819,  5690.81321701,
       37177.51302538, 19582.16490558,  5420.21421031, 41199.19244038,
       11400.14049557, 10568.81287238, 14619.71798809, 46997.66744516,
        3615.07821594, 18723.87533766, 36680.85578552,  5807.70457594,
       20817.34903605, 36589.78414311, 11928.76827328, 19386.0533242 ,
       17440.78777444,  8030.76500329, 13990.43208128,  5853.72858997,
       13967.40101859, 17218.2622258 ,  5603.61907388, 13364.9027199 ,
       11191.48437569,  3782.15108224, 12418.66034313,  8543.64782575,
       20427.05379405])

In [10]:
pred = pd.DataFrame(y_pred)
pred['id'] = range(770, 1439)
pred.columns = ['charges', 'id']
pred.to_csv(r"C:\Users\bas41\Downloads\answer.csv", index=False)